/* 
 * NibblerDX for the Amstrad CPC
 * Copyright (C) 2024 Dave Moore
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include <main.h>

/* Font generated by CPC Telera with image_conversation.mk macros; each tile is
 * 8x8 pixels, which in Mode 1 is 2x8 bytes */
extern const u8 font_000[2 * 8];
extern const u8 font_001[2 * 8];
extern const u8 font_002[2 * 8];
extern const u8 font_003[2 * 8];
extern const u8 font_004[2 * 8];
extern const u8 font_005[2 * 8];
extern const u8 font_006[2 * 8];
extern const u8 font_007[2 * 8];
extern const u8 font_008[2 * 8];
extern const u8 font_009[2 * 8];
extern const u8 font_010[2 * 8];
extern const u8 font_011[2 * 8];
extern const u8 font_012[2 * 8];
extern const u8 font_013[2 * 8];
extern const u8 font_014[2 * 8];
extern const u8 font_015[2 * 8];
extern const u8 font_016[2 * 8];
extern const u8 font_017[2 * 8];
extern const u8 font_018[2 * 8];
extern const u8 font_019[2 * 8];
extern const u8 font_020[2 * 8];
extern const u8 font_021[2 * 8];
extern const u8 font_022[2 * 8];
extern const u8 font_023[2 * 8];
extern const u8 font_024[2 * 8];
extern const u8 font_025[2 * 8];
extern const u8 font_026[2 * 8];
extern const u8 font_027[2 * 8];
extern const u8 font_028[2 * 8];
extern const u8 font_029[2 * 8];
extern const u8 font_030[2 * 8];
extern const u8 font_031[2 * 8];
extern const u8 font_032[2 * 8];
extern const u8 font_033[2 * 8];
extern const u8 font_034[2 * 8];
extern const u8 font_035[2 * 8];
extern const u8 font_036[2 * 8];
extern const u8 font_037[2 * 8];
extern const u8 font_038[2 * 8];
extern const u8 font_039[2 * 8];
extern const u8 font_040[2 * 8];
extern const u8 font_041[2 * 8];
extern const u8 font_042[2 * 8];
extern const u8 font_043[2 * 8];
extern const u8 font_044[2 * 8];
extern const u8 font_045[2 * 8];
extern const u8 font_046[2 * 8];
extern const u8 font_047[2 * 8];
extern const u8 font_048[2 * 8];
extern const u8 font_049[2 * 8];
extern const u8 font_050[2 * 8];
extern const u8 font_051[2 * 8];
extern const u8 font_052[2 * 8];
extern const u8 font_053[2 * 8];
extern const u8 font_054[2 * 8];
extern const u8 font_055[2 * 8];
extern const u8 font_056[2 * 8];
extern const u8 font_057[2 * 8];
extern const u8 font_058[2 * 8];
extern const u8 font_059[2 * 8];
extern const u8 font_060[2 * 8];
extern const u8 font_061[2 * 8];
extern const u8 font_062[2 * 8];
extern const u8 font_063[2 * 8];
extern const u8 font_064[2 * 8];
extern const u8 font_065[2 * 8];
extern const u8 font_066[2 * 8];
extern const u8 font_067[2 * 8];
extern const u8 font_068[2 * 8];
extern const u8 font_069[2 * 8];
extern const u8 font_070[2 * 8];
extern const u8 font_071[2 * 8];
extern const u8 font_072[2 * 8];
extern const u8 font_073[2 * 8];
extern const u8 font_074[2 * 8];
extern const u8 font_075[2 * 8];
extern const u8 font_076[2 * 8];
extern const u8 font_077[2 * 8];
extern const u8 font_078[2 * 8];
extern const u8 font_079[2 * 8];
extern const u8 font_080[2 * 8];
extern const u8 font_081[2 * 8];
extern const u8 font_082[2 * 8];
extern const u8 font_083[2 * 8];
extern const u8 font_084[2 * 8];
extern const u8 font_085[2 * 8];
extern const u8 font_086[2 * 8];
extern const u8 font_087[2 * 8];
extern const u8 font_088[2 * 8];
extern const u8 font_089[2 * 8];
extern const u8 font_090[2 * 8];
extern const u8 font_091[2 * 8];
extern const u8 font_092[2 * 8];
extern const u8 font_093[2 * 8];
extern const u8 font_094[2 * 8];
extern const u8 font_095[2 * 8];
extern const u8 font_096[2 * 8];
extern const u8 font_097[2 * 8];
extern const u8 font_098[2 * 8];
extern const u8 font_099[2 * 8];

extern u8* const font_ts[100];	/* Font table */
