/* 
 * NibblerDX for the Amstrad CPC
 * Copyright (C) 2024 Dave Moore
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include <main.h>

/*
 * Icons generated by CPC Telera with image_conversation.mk macros; each icon is
 * 16x16 pixels, which in Mode 1 is 4x16 bytes
 */
extern const u8 icon_00[4 * 16];
extern const u8 icon_01[4 * 16];
extern const u8 icon_02[4 * 16];
extern const u8 icon_03[4 * 16];
extern const u8 icon_04[4 * 16];
extern const u8 icon_05[4 * 16];
extern const u8 icon_06[4 * 16];
extern const u8 icon_07[4 * 16];
extern const u8 icon_08[4 * 16];
extern const u8 icon_09[4 * 16];

extern u8* const icon_ts[10];		/* Icon Table */

#define BLANK_ICON 9;			/* Fixed Index of blank icon */
